<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:
the visbile layer is is directly put into the neural net, contains one or more features, what the prediction is based on 
### Hidden Layer:
all the additional layers between the input and the output layer 
### Output Layer:
the prediction, as a  result of previous layers 
### Neuron:
a node in the network 
### Weight:
the factor that each input is changed by to make a better prediction 
### Activation Function:
each node has a function that determines whether it "fires" or not, like a sigmoid function, that goes from zero to one 
### Node Map:
the architecture of a neural net 
### Perceptron:
the simplest neural net, one or more inputs, with weights and biases, gives one output. 

## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### the inputs come in and get multiplied by their respective weights, they get are summed up with the bias and then everything is put into an activation function 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [228]:
import pandas as pd
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [355]:
import numpy as np
inputs = np.array(df[['x1', 'x2']])
correct_outputs = np.array(df.y)

In [367]:
weights = (2 * np.random.random((4, 2)) - 1).T

In [368]:
weights

array([[ 0.75796949, -0.90717305,  0.35301318, -0.64808009],
       [-0.20050773,  0.32176938, -0.19543843, -0.87056245]])

In [369]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

for iteration in range(10000):
    
    # Weighted sum of inputs / weights
    weighted_sum = np.dot(inputs, weights)
    
    # Activate!
    activated_output = sigmoid(weighted_sum)
    
    # Cac error
    error = correct_outputs - activated_output
    
    adjustments = error * sigmoid_derivative(activated_output)
    
    # Update the Weights
    weights += np.dot(inputs.T, adjustments)
    
print("Weights after training")
print(weights)

print("Output after training")
print(activated_output)

Weights after training
[[ 7.5873809   7.58549728  7.58684516 -7.82514862]
 [ 7.58578607  7.58727484  7.58599966 -7.82554848]]
Output after training
[[5.00000000e-01 5.00000000e-01 5.00000000e-01 5.00000000e-01]
 [9.99493400e-01 9.99492445e-01 9.99493128e-01 3.99439502e-04]
 [9.99492591e-01 9.99493346e-01 9.99492700e-01 3.99279862e-04]
 [9.99999743e-01 9.99999743e-01 9.99999743e-01 1.59615587e-07]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [370]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [376]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

scaler = MinMaxScaler()

feats = list(diabetes)[:-1]


In [383]:

X = scaler.fit_transform(pd.DataFrame(diabetes[feats]))

In [387]:
y = diabetes.Outcome
y

0      1
1      0
2      1
3      0
4      1
5      0
6      1
7      0
8      1
9      1
10     0
11     1
12     0
13     1
14     1
15     1
16     1
17     1
18     0
19     1
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     0
28     0
29     0
      ..
738    0
739    1
740    1
741    0
742    0
743    1
744    0
745    0
746    1
747    0
748    1
749    1
750    1
751    0
752    0
753    1
754    1
755    1
756    0
757    1
758    0
759    1
760    0
761    1
762    0
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [390]:
##### Update this Class #####

class Perceptron(object):
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)

    def fit(self, X, y):
        inputs = X
        correct_outputs = y

    # Randomly Initialize Weights
    weights = (2 * np.random.random((8, 8)) - 1).T

    for i in range(self.niter):
        weighted_sum = np.dot(inputs, weights)

        activated_output = sigmoid(weighted_sum)

        error = correct_outputs - activated_output
    
        adjustments = error * sigmoid_derivative(activated_output)
        
        weights += np.dot(inputs.T, adjustments)

    def predict(self, X):
        return weights, activated_output

NameError: name 'self' is not defined

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?